export const SET_SERVICE_VALUE = 'SET_SERVICE_VALUE';
export const ADD_SERVICE = 'ADD_SERVICE';
export const DEL_SERVICE = 'DEL_SERVICE';
export const REPLACEMENT_SERVICE = 'REPLACEMENT_SERVICE';
export const EXCHANGE_SERVICE = 'EXCHANGE_SERVICE';